# Generated by Django 4.2.2 on 2023-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
