# Generated by Django 4.2.2 on 2023-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
